import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import "../../app/globals.css";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className=" bg-[#f0ebe5]">
        <div className="flex h-screen overflow-hidden">
          <Sidebar /> {/* Client Component */}
          <div className="flex flex-col flex-1 overflow-auto">
            <div className="max-w-7xl mx-auto w-full">
              <Header /> {/* Client Component */}
              <main>{children}</main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
